name: Build Fira Code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - run: echo "FIRA_CODE_VERSION=$(python3 ./script/version.py)" >> $GITHUB_ENV
    - run: ./script/bootstrap_linux.sh
    - run: ./script/build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: Fira_Code_v${{ env.FIRA_CODE_VERSION }}
        path: distr