on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: tonsky/firacode:latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ${GITHUB_REF#refs/heads/}
    - run: echo "version=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
    - run: ./script/build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: Fira_Code_${{ env.version }}
        path: distr